[buildPlans.jozsika]
family = "Jozsika"
design = ["term"]

[buildPlans.jozsika.weights.regular]
shape = 300
menu  = 400
css   = 400

[buildPlans.jozsika.weights.bold]
shape = 500
menu  = 700
css   = 700

[buildPlans.jozsika.slants]
upright = "normal"
italic = "italic"
# oblique = "oblique"
